### ISSUE TITLE
Extended version info

### ISSUE THREAD

**Issue by samo79** [sodero/MUI-Vim#12]
Current program info about the "version" could be extended a bit more in atleast a couple of places by even adding a release date into it

Current version in Vim at the monent says only something like this:

Vim 8.2.xxxx

But eventually this might be extended by adding a small routine in order to catch the release date, For example to have something like this:

Vim 8.2.xxxx (14.02.2020)

Also that resulted string could be showed in Workbench's titlebar aswell, so users could have an immediate visualization of the specific version currently installed on

**Comment by sodero** [comment]
I think I fixed this but I have no way of verifying that it works on OS4. Does the latest build work for you?

**Comment by samo79** [comment]
Version works (right click on binary now report correctly the version number and the release date)
However that strings still not appear in Workbench titlebar yet

So while first  "issue" is solved, there other not yet

**Comment by sodero** [comment]
Thanks for testing. I need to find out where WB is looking for the version.

**Comment by samo79** [comment]
Probably you will need to use the "MUIA_Window_ScreenTitle"
This will show the text in the screens title bar when the window of the program is active.

https://muidev.de/wiki/Documentation/API/MUI_Window#MUIA_Window_ScreenTitle

**Comment by sodero** [comment]
Thanks for the hint. Should work now, a new build will be available within 10 minutes or se.

**Comment by samo79** [comment]
Yep it works perfectly now, well done!
You can close this ticket aswell :-)
