### ISSUE TITLE
Show VIM icon when iconify the program

### ISSUE THREAD

**Issue by samo79** [sodero/MUI-Vim#9]
Atleast in the OS4 version, the program icon are not show when VIM is iconified.
Currently it will be used the default icon of MUI instead.

**Comment by sodero** [comment]
Thanks for reporting this. Will hopefully have time to fix it in the coming days.

**Comment by sodero** [comment]
Should be fixed in https://github.com/sodero/MUI-Vim/releases/tag/8.2.1743

**Comment by samo79** [comment]
Seems not fixed yet... as you can see from the grab when VIM will be iconified it still be showed the "MUI" icon instead

![grab](https://user-images.githubusercontent.com/29811082/94370017-7ed3f000-00ed-11eb-9228-11aaf264bd02.png)

**Comment by samo79** [comment]
Seems not yet .. i reopen the ticket

**Comment by sodero** [comment]
Did you reinstall Vim or just did you just copy the binary? The Vim_LodsaColorsMason.info must be in VIM:icons for it to work.

**Comment by samo79** [comment]
Yes, I was entirely deleted the whole folder of the old release, then i've just download and installed again the latest release (8.2.1749)
But as you can see in the grab above MUI icon still show instead of the VIM one when i iconify the program

**Comment by sodero** [comment]
Ok, will look into it.

**Comment by sodero** [comment]
Strange. If you do a 'list vim:icons', is there a file called 'Vim_LoadsaColorsMason.info' there?

**Comment by samo79** [comment]
Sorry for delay, i've solved the issue :-)
Aniway, perphaps all that program icons could be picked automatically by the program without the need to use the installer
